### ISSUE TITLE
Occurrence of dependency-management-plugin leads to bad performance

### ISSUE THREAD

**Issue by moley** [spring-gradle-plugins/dependency-management-plugin#222]
Hi

We are facing a performance issue on resolving dependencies with gradle.
We have a large project which we modularize. At the end we will have about 20 modules, each of them is a multi project build with about 10-20 subprojects. We also modularized our framework, which comes along with about 30 subprojects. We are half the way and have dependency resolution times per module of 30 seconds each time. I have done different performance measurements coming to inconclusive results, but all together they are ways to slow. I have uploaded a testproject to github. Details on handling you can see in README.md.
For us this is currently a show stopper for this modularization, so it would be nice to get a solution, workaround or a tip what goes wrong in our scenario asap. If you have problems to reproduce or any further questions, please call.
I have also opened a bug in gradle, because the basic gradle resolution is slow itself, too.
I have uploaded an example project to https://github.com/moley/exampleGradleDepsPerformance were you can check this. A short explanation you get at README.md, don't hesitate to ask if you have further questions
Thanks in advance

Cheers
Markus

**Comment by wilkinsona** [comment]
Thanks for the sample.

The dependency management plugin [attempts to mimic Maven's exclusion semantics](https://github.com/spring-gradle-plugins/dependency-management-plugin#maven-exclusions). To achieve this it needs the poms of all of a configuration's dependencies. The poms are parsed and the modules that should be excluded are identified. The exclusions are then applied to the original configuration before it's resolved.

The poms used to determine the exclusions are obtained by resolving a separate, detached configuration. It's this configuration resolution that's taking the extra time. Basically, you are being bitten twice by Gradle's resolution being slow.

You can avoid the extra configuration resolution by telling the plugin not to apply Maven-style exclusion semantics:

```groovy
dependencyManagement {
    applyMavenExclusions = false
}
```

With this configuration in place, I get approximately the same performance both with and without the dependency management plugin applied. Note that you may need to manually declare some additional exclusions to avoid unwanted transitive dependencies. Please give this a try and let me know how you get on.

**Comment by moley** [comment]
@wilkinsona  
Hi Andy, 
thanks for the workaround. This heavily improves the performance. But we don't know yet if this disabling maven exclusions completely works for us (especially in concerns of Jboss). So we can use it as workaround at the moment, but perhaps we will come to the point were it doesn't work anymore. 
Can you imagine to improve performance at this point e.g. by introducing an index. Because as long as dependencies do not change all exclusions should stay the same, too - don't they?

**Comment by wilkinsona** [comment]
> This heavily improves the performance.

Thanks for the confirmation.

> Can you imagine to improve performance at this point e.g. by introducing an index

Computing the actual exclusions is relatively inexpensive. The cost here is in the resolution of the `Configuration` that's used to read the poms and compute the exclusions. I consider the resolved configuration to already have been "indexed" by Gradle's cache. That's not working quite as well as hoped in that case, but that's a problem that should be addressed in Gradle, rather than this plugin introducing an index of its own.

I'm going to close this one as I believe the underlying problem is the slow configuration resolution and that should be addressed in Gradle.

**Comment by moley** [comment]
Ok, but the slow resolving is the one thing, but the other thing is that when using gradle plain dependencies resolution it seems that the configuration is not resolved anymore in further calls. But as soon as I apply spring dependency plugin this newly created configuration is always completely resolved. As far as I understand you want gradle to provide a way (or automatically do) notice that your configuration must not be resolved anymore. Is this the problem? Did you already create a bug for this problem, should I create one?

**Comment by wilkinsona** [comment]
> But as soon as I apply spring dependency plugin this newly created configuration is always completely resolved. As far as I understand you want gradle to provide a way (or automatically do) notice that your configuration must not be resolved anymore. Is this the problem?

No, that's not the problem.

The dependency management plugin creates one detached configuration for each "proper" configuration that's being resolved. This detached configuration is used to resolve the poms of every dependency in the "proper" configuration. The majority of the time, those poms should have already been downloaded, should be available in Gradle's cache, and, therefore, the resolution of the configuration should be quick.

The configuration is not quick to resolve, even when everything is cached, in the sample that you have provided. That is the problem that I expect to be addressed by Gradle and, I believe, is already covered by the issue that you raised and the issue that is was marked as a duplicate of.

**Comment by wilkinsona** [comment]
In the testing with your sample that I did earlier, I used the local Artifactory via Docker and it was configuration resolution that took the vast majority of the time when the dependency management plugin was applying Maven exclusion semantics. If you've seen something to the contrary then I haven't been able to reproduce it. To spend any more time on this, I'd need to be able to do so.

**Comment by moley** [comment]
No - I didn't go into details, so propably you are right.

**Comment by moley** [comment]
Hi Andy, 
I have profiles into details, and saw, that reading the maven model, which is done by spring dependency plugin is slow at this point (mostly interpolation). I don't know if my example project comes to the same point, the screenshot is from a real project: [https://github.com/moley/exampleGradleDepsPerformance/blob/master/profiler_real_project.png ](pic)

So if you do not see the same in example project, tell me - so I could improve the demo project
